name: Testing Action

on:
  workflow_dispatch:
    inputs:
      a-string:
        description: 'insert something to consume'
        required: true
        default: 'hello world'
  repository_dispatch:
    types: [test-action]

jobs:
  test-action:
    name: Test Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.22.0

      - name: Use Node LTS ✨
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies 📦️
        run: pnpm install --frozen-lockfile

      - name: Build 🔨
        run: pnpm build

      - name: Test Action
        uses: ./
